INSERT INTO Series (id, name, image) VALUES
(1, 'Breaking Bad', 'Breaking Bad.jpg'),
(2, 'Game of Thrones', 'Game of Thrones.jpg'),
(3, 'Chernobyl', 'Chernobyl.jpg'),
(4, 'Band of Brothers', 'Band of Brothers.jpg'),
(5, 'Sherlock', NULL),
(6, 'Rick and Morty', 'Rick and Morty.jpg'),
(7, 'The Wire', 'The Wire.jpg'),
(8, 'Friends', 'Friends.jpg'),
(9, 'The Sopranos', 'The Sopranos.jpg'),
(10, 'True Detective', 'True Detective.jpg'),
(11, 'Stranger Things', 'Stranger Things.jpg'),
(12, 'Avatar: The Last Airbender', NULL),
(13, 'Dexter', NULL),
(14, 'House of Cards', 'House of Cards.jpg'),
(15, 'Firefly', 'Firefly.jpg'),
(16, 'Westworld', NULL),
(17, 'Black Mirror', 'Black Mirror.jpg'),
(18, 'Death Note: Desu nôto', NULL),
(19, 'The Office', 'The Office.jpg'),
(20, 'House M.D.', 'House M.D..jpg'),
(21, 'Arrested Development', 'Arrested Development.jpg'),
(22, 'The Simpsons', 'The Simpsons.jpg'),
(23, 'Peaky Blinders', 'Peaky Blinders.jpg'),
(24, 'Seinfeld', NULL),
(25, 'South Park', NULL),
(26, 'Hagane no renkinjutsushi', 'Hagane no renkinjutsushi.jpg'),
(27, 'Vikings', 'Vikings.jpg'),
(28, 'Better Call Saul', NULL),
(29, 'Daredevil', NULL),
(30, 'The Walking Dead', NULL),
(31, 'It\'s Always Sunny in Philadelphia', NULL),
(32, 'Twin Peaks', NULL),
(33, 'Suits', 'Suits.jpg'),
(34, 'Sons of Anarchy', 'Sons of Anarchy.jpg'),
(35, 'Batman: The Animated Series', NULL),
(36, 'Shingeki no kyojin', NULL),
(37, 'How I Met Your Mother', 'How I Met Your Mother.jpg'),
(38, 'Mr. Robot', NULL),
(39, 'Freaks and Geeks', 'Freaks and Geeks.jpg'),
(40, 'Supernatural', 'Supernatural.jpg'),
(41, 'Downton Abbey', NULL),
(42, 'Rome', 'Rome.jpg'),
(43, 'Battlestar Galactica', 'Battlestar Galactica.jpg'),
(44, 'Lost', 'Lost.jpg'),
(45, 'Doctor Who', 'Doctor Who.jpg'),
(46, 'The X Files', 'The X Files.jpg'),
(47, 'Mad Men', 'Mad Men.jpg'),
(48, 'Parks and Recreation', 'Parks and Recreation.jpg'),
(49, 'The Twilight Zone', 'The Twilight Zone.jpg'),
(50, 'Prison Break', 'Prison Break.jpg'),
(51, 'Modern Family', 'Modern Family.jpg'),
(52, 'Shameless', 'Shameless.jpg'),
(53, 'Kaubôi bibappu', 'Kaubôi bibappu.jpg'),
(54, 'The Haunting of Hill House', 'The Haunting of Hill House.jpg'),
(55, 'Boardwalk Empire', 'Boardwalk Empire.jpg'),
(56, 'The Punisher', 'The Punisher.jpg'),
(57, 'Spartacus: Blood and Sand', NULL),
(58, 'Hannibal', NULL),
(59, 'Pride and Prejudice', 'Pride and Prejudice.jpg'),
(60, 'Six Feet Under', 'Six Feet Under.jpg'),
(61, 'The Big Bang Theory', 'The Big Bang Theory.jpg'),
(62, 'Dragon Ball Z', NULL),
(63, 'Community', 'Community.jpg'),
(64, 'Archer', NULL),
(65, 'Big Little Lies', 'Big Little Lies.jpg'),
(66, 'Gravity Falls', 'Gravity Falls.jpg'),
(67, 'Homeland', 'Homeland.jpg'),
(68, 'Fringe', 'Fringe.jpg'),
(69, 'The Crown', 'The Crown.jpg'),
(70, 'Curb Your Enthusiasm', 'Curb Your Enthusiasm.jpg'),
(71, 'This Is Us', 'This Is Us.jpg'),
(72, 'The Handmaid\'s Tale', NULL),
(73, 'Monty Python\'s Flying Circus', NULL),
(74, 'Fawlty Towers', 'Fawlty Towers.jpg'),
(75, 'Scrubs', 'Scrubs.jpg'),
(76, 'The West Wing', 'The West Wing.jpg'),
(77, 'Brooklyn Nine-Nine', 'Brooklyn Nine-Nine.jpg'),
(78, 'The IT Crowd', 'The IT Crowd.jpg'),
(79, 'Spartacus: Gods of the Arena', NULL),
(80, 'Only Fools and Horses....', 'Only Fools and Horses.....jpg'),
(81, 'Star Trek: The Next Generation', NULL),
(82, 'Person of Interest', 'Person of Interest.jpg'),
(83, 'Entourage', 'Entourage.jpg'),
(84, 'Deadwood', NULL),
(85, 'The Shield', NULL);